[project]
name = "pc-builder-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
	"langgraph>=0.2.0",
	"langchain-openai>=0.3.0",
	"langchain-google-genai>=0.3.0",
	"python-dotenv>=1.0.0",
	"requests>=2.32.0",
	"beautifulsoup4>=4.12.0",
]

[project.scripts]
pc-builder-agent = "pc_builder_agent.cli:main"
node-tester = "pc_builder_agent.tools.node_tester:main"

[tool.uv]
package = true
