"""
電子商城示範資料 (seed data)。

此模組只負責「資料」,不含任何資料庫邏輯,方便與 ecommerce_db.py 解耦。
ecommerce_db.load_seed_products() 會 import DEFAULT_SEED_PRODUCTS 並寫入 SQLite。

欄位說明(對應 products 表):
- source           : 商城 / 店家名稱(示範用,非真實爬蟲結果)
- category         : 零件類別(CPU / GPU / Motherboard)
- product_name     : 商品完整名稱
- brand            : 品牌
- model            : 型號(原始字串,可有空白或大小寫差異)
- price            : 目前售價(整數,新台幣)
- original_price   : 原價(可為 None)
- discount_price   : 特價(可為 None;有值且 < original_price 視為單品特價)
- url              : 商品頁面網址(可留空,留空時去重改用 source+category+product_name)
- specs            : 規格(dict,寫入時會被序列化成 JSON 字串)
- stock_status     : 庫存狀態
- bundle_id        : 套裝組合 ID(第一階段一律留空,欄位保留給未來)

注意:這裡「不」提供 model_key;model_key 由 ecommerce_db 在寫入時自動正規化產生,
這樣才能驗證 "RTX 4060" / "rtx4060" / "RTX-4060" 都能被正規化成相同 key。
"""

from __future__ import annotations


DEFAULT_SEED_PRODUCTS: list[dict] = [
    # ===================== CPU =====================
    {
        "source": "原價屋",
        "category": "CPU",
        "product_name": "AMD Ryzen 7 7800X3D",
        "brand": "AMD",
        "model": "Ryzen 7 7800X3D",
        "price": 11990,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/coolpc/cpu/7800x3d",
        "specs": {"cores": 8, "threads": 16, "socket": "AM5", "tdp": 120},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "原價屋",
        "category": "CPU",
        "product_name": "AMD Ryzen 5 7600",
        "brand": "AMD",
        "model": "Ryzen 5 7600",
        "price": 6490,
        "original_price": 6990,
        "discount_price": 6490,  # 單品特價
        "url": "https://example.com/coolpc/cpu/7600",
        "specs": {"cores": 6, "threads": 12, "socket": "AM5", "tdp": 65},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "欣亞",
        "category": "CPU",
        "product_name": "Intel Core i5-14600K",
        "brand": "Intel",
        "model": "Core i5-14600K",
        "price": 9290,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/sinya/cpu/14600k",
        "specs": {"cores": 14, "threads": 20, "socket": "LGA1700", "tdp": 125},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "欣亞",
        "category": "CPU",
        "product_name": "Intel Core i7-14700K",
        "brand": "Intel",
        "model": "Core i7-14700K",
        "price": 13900,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/sinya/cpu/14700k",
        "specs": {"cores": 20, "threads": 28, "socket": "LGA1700", "tdp": 125},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "原價屋",
        "category": "CPU",
        "product_name": "AMD Ryzen 5 5600",
        "brand": "AMD",
        "model": "Ryzen 5 5600",
        "price": 3450,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/coolpc/cpu/5600",
        "specs": {"cores": 6, "threads": 12, "socket": "AM4", "tdp": 65},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "欣亞",
        "category": "CPU",
        "product_name": "Intel Core i3-14100",
        "brand": "Intel",
        "model": "Core i3-14100",
        "price": 3990,
        "original_price": None,
        "discount_price": None,
        "url": "",  # 故意留空,測試 source+category+product_name 去重備援
        "specs": {"cores": 4, "threads": 8, "socket": "LGA1700", "tdp": 60},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "原價屋",
        "category": "CPU",
        "product_name": "AMD Ryzen 9 7950X",
        "brand": "AMD",
        "model": "Ryzen 9 7950X",
        "price": 17900,
        "original_price": 19900,
        "discount_price": 17900,  # 單品特價
        "url": "https://example.com/coolpc/cpu/7950x",
        "specs": {"cores": 16, "threads": 32, "socket": "AM5", "tdp": 170},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "欣亞",
        "category": "CPU",
        "product_name": "Intel Core i5-13400F",
        "brand": "Intel",
        "model": "Core i5-13400F",
        "price": 5990,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/sinya/cpu/13400f",
        "specs": {"cores": 10, "threads": 16, "socket": "LGA1700", "tdp": 65},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    # ===================== GPU =====================
    {
        "source": "原價屋",
        "category": "GPU",
        "product_name": "華碩 DUAL RTX 4060 O8G",
        "brand": "ASUS",
        "model": "RTX 4060",
        "price": 9290,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/coolpc/gpu/rtx4060",
        "specs": {"vram": "8GB", "tdp": 115, "chipset": "NVIDIA"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "欣亞",
        "category": "GPU",
        "product_name": "微星 RTX 4060 Ti VENTUS 2X",
        "brand": "MSI",
        "model": "RTX-4060-Ti",  # 故意用連字號,測試 model_key 正規化
        "price": 12900,
        "original_price": 13900,
        "discount_price": 12900,  # 單品特價
        "url": "https://example.com/sinya/gpu/rtx4060ti",
        "specs": {"vram": "8GB", "tdp": 160, "chipset": "NVIDIA"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "原價屋",
        "category": "GPU",
        "product_name": "技嘉 RTX 4070 SUPER GAMING OC",
        "brand": "GIGABYTE",
        "model": "RTX 4070 Super",
        "price": 19900,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/coolpc/gpu/rtx4070super",
        "specs": {"vram": "12GB", "tdp": 220, "chipset": "NVIDIA"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "欣亞",
        "category": "GPU",
        "product_name": "撼訊 RX 7600 HellHound",
        "brand": "PowerColor",
        "model": "RX 7600",
        "price": 8290,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/sinya/gpu/rx7600",
        "specs": {"vram": "8GB", "tdp": 165, "chipset": "AMD"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "原價屋",
        "category": "GPU",
        "product_name": "華碩 TUF RX 7800 XT O16G",
        "brand": "ASUS",
        "model": "RX 7800 XT",
        "price": 16900,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/coolpc/gpu/rx7800xt",
        "specs": {"vram": "16GB", "tdp": 263, "chipset": "AMD"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "欣亞",
        "category": "GPU",
        "product_name": "微星 RTX 4070 GAMING X SLIM",
        "brand": "MSI",
        "model": "rtx4070",  # 故意全小寫無空白,測試 model_key 正規化
        "price": 17500,
        "original_price": 18900,
        "discount_price": 17500,  # 單品特價
        "url": "https://example.com/sinya/gpu/rtx4070",
        "specs": {"vram": "12GB", "tdp": 200, "chipset": "NVIDIA"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "原價屋",
        "category": "GPU",
        "product_name": "技嘉 RTX 3060 GAMING OC 12G",
        "brand": "GIGABYTE",
        "model": "RTX 3060",
        "price": 7990,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/coolpc/gpu/rtx3060",
        "specs": {"vram": "12GB", "tdp": 170, "chipset": "NVIDIA"},
        "stock_status": "low_stock",
        "bundle_id": "",
    },
    {
        "source": "欣亞",
        "category": "GPU",
        "product_name": "華碩 ROG STRIX RTX 4090 O24G",
        "brand": "ASUS",
        "model": "RTX 4090",
        "price": 58900,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/sinya/gpu/rtx4090",
        "specs": {"vram": "24GB", "tdp": 450, "chipset": "NVIDIA"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    # ===================== Motherboard =====================
    {
        "source": "原價屋",
        "category": "Motherboard",
        "product_name": "華碩 TUF GAMING B650-E WIFI",
        "brand": "ASUS",
        "model": "B650-E",
        "price": 6990,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/coolpc/mb/b650e",
        "specs": {"socket": "AM5", "form_factor": "ATX", "memory": "DDR5"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "欣亞",
        "category": "Motherboard",
        "product_name": "微星 MAG B760M MORTAR WIFI",
        "brand": "MSI",
        "model": "B760M MORTAR",
        "price": 4990,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/sinya/mb/b760m-mortar",
        "specs": {"socket": "LGA1700", "form_factor": "mATX", "memory": "DDR5"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "原價屋",
        "category": "Motherboard",
        "product_name": "技嘉 B650 AORUS ELITE AX",
        "brand": "GIGABYTE",
        "model": "B650 AORUS ELITE AX",
        "price": 5990,
        "original_price": 6490,
        "discount_price": 5990,  # 單品特價
        "url": "https://example.com/coolpc/mb/b650-aorus-elite",
        "specs": {"socket": "AM5", "form_factor": "ATX", "memory": "DDR5"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "欣亞",
        "category": "Motherboard",
        "product_name": "華碩 PRIME B760-PLUS",
        "brand": "ASUS",
        "model": "B760-PLUS",
        "price": 4290,
        "original_price": None,
        "discount_price": None,
        "url": "",  # 故意留空,測試去重備援
        "specs": {"socket": "LGA1700", "form_factor": "ATX", "memory": "DDR5"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "原價屋",
        "category": "Motherboard",
        "product_name": "微星 MAG X670E TOMAHAWK WIFI",
        "brand": "MSI",
        "model": "X670E TOMAHAWK",
        "price": 9990,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/coolpc/mb/x670e-tomahawk",
        "specs": {"socket": "AM5", "form_factor": "ATX", "memory": "DDR5"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "欣亞",
        "category": "Motherboard",
        "product_name": "華擎 B650M PG Lightning",
        "brand": "ASRock",
        "model": "B650M PG Lightning",
        "price": 3990,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/sinya/mb/b650m-pg",
        "specs": {"socket": "AM5", "form_factor": "mATX", "memory": "DDR5"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "原價屋",
        "category": "Motherboard",
        "product_name": "華碩 ROG STRIX Z790-A GAMING WIFI",
        "brand": "ASUS",
        "model": "Z790-A",
        "price": 12900,
        "original_price": 13900,
        "discount_price": 12900,  # 單品特價
        "url": "https://example.com/coolpc/mb/z790-a",
        "specs": {"socket": "LGA1700", "form_factor": "ATX", "memory": "DDR5"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
    {
        "source": "欣亞",
        "category": "Motherboard",
        "product_name": "技嘉 B760M DS3H DDR4",
        "brand": "GIGABYTE",
        "model": "B760M DS3H",
        "price": 3290,
        "original_price": None,
        "discount_price": None,
        "url": "https://example.com/sinya/mb/b760m-ds3h",
        "specs": {"socket": "LGA1700", "form_factor": "mATX", "memory": "DDR4"},
        "stock_status": "in_stock",
        "bundle_id": "",
    },
]
